apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-service
  labels:
    app: explorviz
    run: adapter-service
spec:
  replicas: {{ .Values.adapter.replicaCount }}
  selector:
    matchLabels:
      app: explorviz
      run: adapter-service
  template:
    metadata:
      labels:
        app: explorviz
        run: adapter-service
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: adapter-service
          image: "{{ .Values.image.adapter }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.adapter.port }}
              name: http
          env:
            {{- range $key, $value := .Values.adapter.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          
          # readinessProbe:
          #   httpGet:
          #     path: /q/health
          #     port: {{ .Values.adapter.port }}
          #   initialDelaySeconds: 15
          #   periodSeconds: 5

