apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-service
  labels:
    app: explorviz
    run: collaboration-service
spec:
  replicas: {{ .Values.collaboration.replicaCount }}
  selector:
    matchLabels:
      app: explorviz
      run: collaboration-service
  template:
    metadata:
      labels:
        app: explorviz
        run: collaboration-service
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: collaboration-service
          image: "{{ .Values.image.collaboration }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.collaboration.port }}
              name: http
          env:
            {{- range $key, $value := .Values.collaboration.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}

          # ✅ Optional health checks
          # readinessProbe:
          #   httpGet:
          #     path: /q/health
          #     port: {{ .Values.collaboration.port }}
          #   initialDelaySeconds: 10
          #   periodSeconds: 5

          # livenessProbe:
          #   httpGet:
          #     path: /q/health/live
          #     port: {{ .Values.collaboration.port }}
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
