apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: explorviz
    run: grafana
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      app: explorviz
      run: grafana
  template:
    metadata:
      labels:
        app: explorviz
        run: grafana
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: grafana
          image: "{{ .Values.image.grafana }}:{{ .Values.image.grafanaTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.grafana.port }}
              name: http
          env:
            {{- range $key, $value := .Values.grafana.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-provisioning
          configMap:
            name: grafana-provisioning
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
