apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: explorviz
    run: otel-collector
spec:
  replicas: {{ .Values.otelCollector.replicaCount }}
  selector:
    matchLabels:
      app: explorviz
      run: otel-collector
  template:
    metadata:
      labels:
        app: explorviz
        run: otel-collector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: otel-collector
          image: "{{ .Values.image.otelCollector }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          args: ["--config=/etc/otel-collector-config.yaml"]
          ports:
            - containerPort: {{ .Values.otelCollector.ports.main }}
              name: otlp
            - containerPort: {{ .Values.otelCollector.ports.zpages }}
              name: zpages
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector-config
