apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: explorviz
    run: prometheus
spec:
  replicas: {{ .Values.prometheus.replicaCount }}
  selector:
    matchLabels:
      app: explorviz
      run: prometheus
  template:
    metadata:
      labels:
        app: explorviz
        run: prometheus
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: prometheus
          image: "{{ .Values.image.prometheus }}:{{ .Values.image.prometheusTag }}"
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
          ports:
            - containerPort: {{ .Values.prometheus.port }}
              name: http
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data
