apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-db
  labels:
    app: teastore
    run: teastore-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: teastore
      run: teastore-db
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-db
    spec:
      containers:
        - name: teastore-db
          image: "{{ .Values.image.db }}:{{ .Values.image.tag }}"
          ports:
            - name: mysql
              containerPort: {{ .Values.db.port }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.db.resources.requests.cpu }}
              memory: {{ .Values.db.resources.requests.memory }}
            limits:
              cpu: {{ .Values.db.resources.limits.cpu }}
              memory: {{ .Values.db.resources.limits.memory }}
