apiVersion: v1
kind: Service
metadata:
  name: teastore-jmeter
  labels:
    app: teastore
    run: teastore-jmeter
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: teastore
    run: teastore-jmeter
