# ---------- Images ----------
image:
  adapter: explorviz/adapter-service-jvm
  span: explorviz/span-service-jvm
  user: explorviz/user-service-jvm
  collaboration: explorviz/collaboration-service
  frontend: explorviz/frontend
  redis: redis
  redisTag: 7.2.2
  kafka: confluentinc/cp-kafka
  schemaRegistry: confluentinc/cp-schema-registry
  otelCollector: "kieker/opentelemetry-collector"
  cassandra: "cassandra"
  mongo: "mongo"
  prometheus: "prom/prometheus"
  kafkaLagExporter: "seglo/kafka-lag-exporter"
  grafana: "grafana/grafana"
  grafanaTag: "latest"
  kafkaLagExporterTag: "0.8.2"
  prometheusTag: "latest"
  mongoTag: "6.0"
  kafkaTag: 7.3.0
  schemaRegistryTag: 7.3.0
  cassandraTag: "3.11.14"
  tag: kieker-2025

# ---------- Global Service Defaults ----------
service:
  type: ClusterIP

# ---------- Adapter Service ----------
adapter:
  port: 8087
  replicaCount: 1    # from ADAPTER_REPLICAS
  env:
    QUARKUS_KAFKA_STREAMS_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    EXPLORVIZ_LOG_LVL: "DEBUG"
    EXPLORVIZ_VALIDATE_TOKEN_EXISTENCE: "true"

# ---------- Span Service ----------
span:
  port: 8080
  replicaCount: 1   
  env:
    QUARKUS_CASSANDRA_CONTACT_POINTS: "cassandra:9042"
    QUARKUS_CASSANDRA_AUTH_USERNAME: "cassandra"
    QUARKUS_CASSANDRA_AUTH_PASSWORD: "cassandra"
    QUARKUS_CASSANDRA_REQUEST_TIMEOUT: "10"
    QUARKUS_KAFKA_STREAMS_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    EXPLORVIZ_LOG_LVL: "DEBUG"
    EXPLORVIZ_SPAN_API_TIME_RANGES_ENABLED: "true"

# ---------- User Service ----------
user:
  port: 8080
  replicaCount: 1 
  env:
    QUARKUS_OIDC_ENABLED: "false"
    INIT_TOKEN_ENABLED: "true"
    INIT_TOKEN_VALUE: "mytokenvalue"
    INIT_TOKEN_SECRET: "mytokensecret"
    MP_MESSAGING_OUTGOING_TOKEN_EVENTS_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    QUARKUS_MONGODB_CONNECTION_STRING: "mongodb://mongo-user:27017"
    EXPLORVIZ_LOG_LVL: "DEBUG"

# ---------- Collaboration Service ----------
collaboration:
  port: 4444
  replicaCount: 1
  env:
    REDIS_HOST: "redis-collab"
    REDIS_PORT: "6379"

  # ---------- Redis Collab Service ----------
redis:
  port: 6379
  replicaCount: 1


# ---------- Frontend Service ----------
frontend:
  port: 8082
  replicaCount: 1
  env:
    FRONTEND_HOST_URL: "http://localhost:80"
    FRONTEND_HOST_NAME: "localhost"
    CODE_SERV_URL: "http://localhost:80"
    LANDSCAPE_URL: "http://span-service:8080"
    TRACE_URL: "http://span-service:8080"
    TIMESTAMPS_URL: "http://span-service:8080"
    USER_URL: "http://user-service:8080"
    COLLABORATION_URL: "http://collaboration-service:4444"
    VSCODE_SERV_URL: "http://localhost:80"
    AUTH0_LOGO_URL: "http://localhost:8080/images/explorviz-logo.png"
    AUTH0_CALLBACK_URL: "http://localhost:8080/callback"
    AUTH0_LOGOUT_URL: "http://localhost:8080/"
    NO_AUTH_USER_NICKNAME: "user-1"

# ---------- Kafka  Service ----------
kafka:
  replicaCount: 1
  ports:
    internal: 9092
    external: 9091
    controller: 29093
    jmx: 9101
  storage:
    size: 5Gi
  env:
    KAFKA_BROKER_ID: "1"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    KAFKA_JMX_PORT: "9101"
    KAFKA_JMX_HOSTNAME: "localhost"
    KAFKA_PROCESS_ROLES: "broker,controller"
    KAFKA_MESSAGE_MAX_BYTES: "10485880"
    KAFKA_NODE_ID: "1"
    KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:29093"
    KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093"
    KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
    KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"


# ----------  Schema Registry  ----------
schemaRegistry:
  port: 8081
  replicaCount: 1
  env:
    SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"
    SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    SCHEMA_REGISTRY_HOST_NAME: 127.0.0.1
# ----------  Otel Collector  ----------
otelCollector:
  replicaCount: 1
  ports:
    main: 55678
    zpages: 55679


# ----------  Cassandra  ----------
cassandra:
  replicaCount: 1
  port: 9042
  storage:
    size: 5Gi
  env:
    MAX_HEAP_SIZE: "1G"
    HEAP_NEWSIZE: "200M"

# ----------  MongoDB User  ----------
mongoUser:
  replicaCount: 1
  port: 27017
  storage:
    data: 2Gi
    config: 500Mi

# ----------  Prometheus  ----------   
prometheus:
  replicaCount: 1
  port: 9090
  storage:
    size: 5Gi

 # ----------  Kafka Lag Exporter  ----------   
kafkaLagExporter:
  replicaCount: 1
  port: 8000

 # ----------  Grafana  ---------- 

grafana:
  replicaCount: 1
  port: 3000
  storage:
    size: 2Gi
  env:
    GF_AUTH_DISABLE_LOGIN_FORM: "true"
    GF_AUTH_ANONYMOUS_ENABLED: "true"
    GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
    GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    GF_USERS_ALLOW_SIGN_UP: "false"
    GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/explorviz-all.json"


# ---------- Monitoring ----------
monitoring:
  prometheusPort: 9090
  nodeExporterPort: 9100
  cadvisorPort: 8080
  grafanaPort: 3000
